### ISSUE TITLE
[UI/UX] Color contrast on navbar items

### ISSUE THREAD

**Issue by binayachaudari** [ThreeDify/ThreeDify-web-app#28]
`font-color` used for navbar items `Dashboard` and `Explore` is causing eye strain. 

<img width="222" alt="Screen Shot 2020-11-13 at 12 54 01" src="https://user-images.githubusercontent.com/10462507/99039975-70b03500-25b0-11eb-98ea-45929da6f8eb.png">

Make sure the color of the text is distinguishable from the background color. 

**Less is more** — Use bright colors sparingly! Rather than using big blocks of color everywhere, limit their use for only the important places that you want to direct the user's eyes

**Comment by KGhising** [comment]
Applied change on navbar
